In [1]:
# Importando bibliotecas

import pandas as pd

import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import plotly.express as px
import yfinance as yf
from selenium.webdriver import Firefox, FirefoxOptions
from selenium.webdriver.common.by import By
import pandas as pd
import time

In [2]:

url = 'https://hedgefollow.com/funds/Berkshire+Hathaway'

options = FirefoxOptions()
# options.headless = True
options.add_argument('-headless')


driver = Firefox(options=options)
driver.get(url)

time.sleep(3)

table = driver.find_element(By.ID, 'dgtopHolders')

headers = []
rows = []
#print('--- headers ---')
header_row = table.find_elements(By.TAG_NAME, 'tr')[0]
for cell in header_row.find_elements(By.TAG_NAME, 'th'):
    headers.append(cell.text)

# print(headers)

# print('--- data ---')
data_rows = table.find_elements(By.TAG_NAME, 'tr')[1:]
for row in data_rows:
    row_data = {}
    for i, cell in enumerate(row.find_elements(By.TAG_NAME, 'td')):
        row_data[headers[i]] = cell.text
    rows.append(row_data)
    #print(row_data)

driver.quit()

df_bh = pd.DataFrame(rows)


df_bh.head()

,Stock,Company Name,% of Portfolio,Shares Owned,Value,Change in Shares,Ownership History,Average Buy Price,Price History,Date
0,AAPL,Apple Inc,38.90%,895.14M,$ 116.31B,0.04% (+333.86k),,$36.98 (+333.3%),,2022-12-31
1,BAC,Bk Of America Corp,11.19%,1.01B,$ 33.45B,0%,,$25.66 (+5.8%),,2022-12-31
2,CVX,Chevron Corp New,9.78%,162.98M,$ 29.25B,-1.44% (-2.38M),,$122.55 (+27.3%),,2022-12-31
3,KO,Coca Cola Co,8.51%,400M,$ 25.44B,0%,,$40.28 (+51.2%),,2022-12-31
4,AXP,American Express Co,7.49%,151.61M,$ 22.40B,0%,,$71.11 (+124.7%),,2022-12-31

In [3]:
df_bh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Stock              49 non-null     object
 1   Company Name       49 non-null     object
 2   % of Portfolio     49 non-null     object
 3   Shares Owned       49 non-null     object
 4   Value              49 non-null     object
 5   Change in Shares   49 non-null     object
 6   Ownership History  49 non-null     object
 7   Average Buy Price  49 non-null     object
 8   Price History      49 non-null     object
 9   Date               49 non-null     object
dtypes: object(10)
memory usage: 4.0+ KB

In [4]:
# Eliminando las columnas innecesarias
df_bh = df_bh.drop(['Ownership History', 'Average Buy Price', 'Price History'], axis=1)

In [5]:
df_bh.head()

,Stock,Company Name,% of Portfolio,Shares Owned,Value,Change in Shares,Date
0,AAPL,Apple Inc,38.90%,895.14M,$ 116.31B,0.04% (+333.86k),2022-12-31
1,BAC,Bk Of America Corp,11.19%,1.01B,$ 33.45B,0%,2022-12-31
2,CVX,Chevron Corp New,9.78%,162.98M,$ 29.25B,-1.44% (-2.38M),2022-12-31
3,KO,Coca Cola Co,8.51%,400M,$ 25.44B,0%,2022-12-31
4,AXP,American Express Co,7.49%,151.61M,$ 22.40B,0%,2022-12-31

In [ ]:

# Guardando el DataFrame en un archivo CSV
df_bh.to_csv('data/berkshire_porfolio.csv', index=False)